base_model: Qwen/Qwen3-14B
# Automatically upload checkpoint and final model to HF
hub_model_id: Rexhaif/Qwen3-14B-MTEval-SFT


load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: tokenizer_default
datasets:
  - path: Rexhaif/wmt23-pairs-sft
    split: "train"
    type: chat_template
    field_messages: messages
    roles_to_train: ["assistant"]

shuffle_merged_datasets: true

skip_prepare_dataset: false
dataset_prepared_path: ./data/wmt23-pairs-sft
output_dir: /hnvme/workspace/v106be28-outputs/sft-14b

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 512
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: llm-reasoning-mt-eval
wandb_entity:
wandb_name: qwen3-14b-sft

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: true
gradient_accumulation_steps: 8
micro_batch_size: 8  # should match num_generations / num_gpus

optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 5.0e-5
cosine_min_lr_ratio: 1.0e-7
max_grad_norm: 1.0
weight_decay: 0.1

bf16: true
tf32: true

flash_attention: true
flash_attn_fuse_qkv: true
flash_attn_fuse_mlp: true
auto_resume_from_checkpoints: true

n_epochs: 3
logging_steps: 10
warmup_ratio: 0.1
evals_per_epoch: 10
saves_per_epoch: 10
save_total_limit: 1
#max_steps: 5000
seed: 42
val_set_size: 0.01

gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
