base_model: Qwen/Qwen2.5-1.5B-Instruct
# Automatically upload checkpoint and final model to HF
hub_model_id: Rexhaif/Qwen2.5-1.5B-MT-Eval-Reasoner

load_in_8bit: false
load_in_4bit: false
strict: false

torch_compile: false

rl: grpo
trl:
  beta: 0.001
  max_completion_length: 768
  use_vllm: true
  reward_funcs:
    - metric_utils.reward_answer_correctness
    - metric_utils.reward_format_correctness
    - metric_utils.choice_reward
  vllm_gpu_memory_utilization: 0.9
  vllm_max_model_len: 1024
  vllm_enable_prefix_caching: false
  num_generations: 32

chat_template: qwen_25
datasets:
  - path: Rexhaif/wmt23-pairs
    type: metric_utils.pairwise_ranking_grpo_transform

dataset_prepared_path: /workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: ./outputs/default

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 1024
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: llm-reasoning-mt-eval
wandb_entity:
wandb_name:

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: true

gradient_accumulation_steps: 4
micro_batch_size: 32  # should match num_generations / num_gpus

optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 1.0e-6
max_grad_norm: 1.0
weight_decay: 0.1

bf16: true
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true
flash_attn_fuse_qkv: true
flash_attn_fuse_mlp: true

logging_steps: 25
warmup_steps: 500
eval_steps: 1000
save_steps: 1000
max_steps: 5000
seed: 42
val_set_size: 0.0001