hydra:
  job:
    chdir: False

competition: "wmt24"
language_pairs: ["ja-zh", "en-de", "en-es"]
traces_sample_size: 100
outputs_dir: llm-reasoning-metric/evals

experiment:
  # 0
  model: "Rexhaif/Qwen3-4B-MT-Eval"
  model_id: "qwen3-4b-v6"
  kind: "mt-ranking" # or gemba-da-like, gemba-esa
  reasoning_effort: "unbounded"
  
  sampling_params:
    temperature: 0.6
    max_tokens: 16384
    top_p: 0.95
    top_k: 20
    presence_penalty: 0.5

