hydra:
  job:
    chdir: False

datasets:
  - file: data/mt-eval.parquet
    kind: mt-ranking
    source_dataset: Rexhaif/wmt22-23-pairs
    max_samples: -1
    subsets:
      - wmt23_da_sqm
  - file: data/deepscaler.parquet
    kind: math
    source_dataset: agentica-org/DeepScaleR-Preview-Dataset
    max_samples: -1
    problem_column: problem
    answer_column: answer
  - file: data/mt-eval-test.parquet
    kind: mt-ranking
    source_dataset: Rexhaif/wmt22-23-pairs
    max_samples: 1000
    subsets:
      - wmt23_mqm
