hydra:
  job:
    chdir: False

llm:
  model: bullerwins/Magistral-Small-2506-fp8
  temperature: 0.7
  max_tokens: 10240
  top_p: 0.95
  top_k: 40

dataset:
  path: data/mt-eval.parquet
  subsample: -1
  n_shards: 10
  shard_id: 0
  output_path: data/sft/mt-eval-0.parquet
  